services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: production
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - ADMIN_USER=${ADMIN_USER}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: production
    ports:
      - "127.0.0.1:${FRONTEND_PORT}:80"
    depends_on:
      - backend
