services:
  backend:
    container_name: peke-panel-back-dev
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: development
    volumes:
      - ./backend:/app
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - ADMIN_USER=${ADMIN_USER}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
    ports:
      - "8000:8000"

  frontend:
    container_name: peke-panel-front-dev
    build:
      context: ./frontend_${FRONTEND_VERSION}
      dockerfile: Dockerfile
      target: development
    volumes:
      - ./frontend_${FRONTEND_VERSION}:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - backend
    command: sh -c "npm start"